-- DROP TABLES (WARNING: Deletes all data)
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS traffic_campaigns;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS payment_methods;
DROP TABLE IF EXISTS sales; -- Deprecated, replaced by income
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS robots;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS clients;

-- 1. Payment Methods (Global)
CREATE TABLE payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, -- Pix, Cartão, Boleto, etc.
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Profiles (Affiliates/Users)
CREATE TABLE profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL, -- admin, seller
  status TEXT NOT NULL, -- active, inactive
  sales INTEGER DEFAULT 0,
  total_sold NUMERIC DEFAULT 0,
  code TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Clients
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, -- Empresa
  plan TEXT NOT NULL,
  status TEXT NOT NULL, -- active, paused, cancelled
  seller TEXT NOT NULL, -- Vendedor responsável
  start_date DATE NOT NULL,
  observations TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Robots
CREATE TABLE robots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE, -- Linked to Client
  client_name TEXT, -- Denormalized for easier listing if needed
  type TEXT NOT NULL,
  plan TEXT,
  status TEXT NOT NULL, -- active, disconnected, maintenance
  whatsapp_number TEXT,
  credits_consumed INTEGER DEFAULT 0,
  renewal_date DATE,
  last_connection TIMESTAMP WITH TIME ZONE,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Traffic Campaigns
CREATE TABLE traffic_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  platform TEXT NOT NULL, -- Google Ads, Meta Ads, TikTok Ads
  status TEXT NOT NULL, -- active, paused
  monthly_budget NUMERIC NOT NULL,
  objective TEXT,
  start_date DATE NOT NULL,
  end_date DATE,
  observations TEXT,
  manager TEXT, -- Responsável
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Documents
CREATE TABLE documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- Contrato, Proposta, Relatório, Nota Fiscal
  url TEXT NOT NULL, -- URL do arquivo
  uploaded_by TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Income (Receitas)
CREATE TABLE income (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  client_name TEXT, -- Denormalized
  plan TEXT,
  type TEXT NOT NULL, -- Implementação, Mensalidade, Anual, Extra
  value NUMERIC NOT NULL,
  billing_date DATE NOT NULL,
  payment_date DATE,
  payment_method TEXT,
  status TEXT NOT NULL, -- paid, open, overdue
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 8. Expenses (Despesas)
CREATE TABLE expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL, -- Tráfego pago, Ferramentas, Infraestrutura, Marketing, Comissão
  description TEXT NOT NULL,
  value NUMERIC NOT NULL,
  date DATE NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL, -- Opcional
  payment_method TEXT,
  status TEXT NOT NULL, -- paid, pending
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 9. Audit Logs (Histórico)
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL, -- Criação, Alteração, Upload
  entity_type TEXT NOT NULL, -- client, robot, financial
  entity_id BIGINT,
  user_name TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 10. Appointments (Legacy/Optional)
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  seller_name TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 11. Conversations (Legacy/Optional)
CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_name TEXT NOT NULL,
  lead_number TEXT NOT NULL,
  robot_name TEXT NOT NULL,
  seller_name TEXT NOT NULL,
  last_message TEXT,
  last_message_time TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Initial Data for Payment Methods
INSERT INTO payment_methods (name) VALUES ('Pix'), ('Cartão de Crédito'), ('Boleto'), ('Transferência'), ('Dinheiro');
